### ISSUE TITLE
Unable to connect via Ogmios

### ISSUE THREAD

**Issue by jeremybarnes2342** [CardanoSolutions/kupo#128]
I'm attempting to connect to Ogmios via the following command:
```
./kupo \ 
--since origin \
--defer-db-indexes \
--match "*" \
--workdir ./db \
--prune-utxo \
--ogmios-host ogmios-api.mainnet.dandelion.link \
--ogmios-port 443
```

However I keep getting the following error:
```
kupo: MalformedResponse (ResponseHead {responseCode = 400, responseMessage = "Bad Request", responseHeaders = [("Date","Thu, 20 Jul 2023 17:38:16 GMT"),("Content-Type","text/html"),("Content-Length","248"),("Connection","close")]}) "Wrong response status or message."
```

Things i've tried:
1) Switching the port from 443 to 1337 (as that seems to be the default port, but the connection just times out).
2) Connecting to Ogmios from my Demeter.run endpoint, and I get the same results.
3) Adding `https://` and `wss://` in front of the Ogmios host but that doesn't help either.

Any ideas what I may be doing wrong?

**Comment by KtorZ** [comment]
Sadly due to the underlying websocket library that Kupo relies on to connect to Ogmios which ... doesn't support connections over TLS ( https://github.com/jaspervdj/websockets/issues/41 ). 

Sounds like there it is possible through other libraries ( e.g. https://taylor.fausak.me/wuss/ ) that could facilitate this. I can give it a try.
