### ISSUE TITLE
[Question] Should start command be idempotent?

### ISSUE THREAD

**Issue by longngn** [CardanoSolutions/kupo#2]
Currently, there is a difference between first-time start and non first-time start.
First time start expect an empty `--workdir` directory and `--since` flag. If `--workdir` doesn't exist then Kupo will fail. This is contrary to `cardano-node` which will create DB dir for you if not exist.
Second+ time start expect to not have `--since` flag. If there are both checkpoints in DB and `--since` then Kupo will fail.

My proposal is that the command should be idempotent. When Kupo is started, it will check for existence of `--workdir`.
If `--workdir` doesn't exist, it will create `--workdir` and sync from `--since`
If `--workdir` exists, it will sync from a list of both checkpoints and `--since`. (`--since` will be appended to the end of checkpoint list)

Currently, to work around, we write a Bash script like so:
```bash
DB_DIR="./db"

if [ ! -d $DB_DIR ]; then
  mkdir "$DB_DIR"
  kupo \
    --node-socket node.sock \
    --node-config config.json \
    --workdir $DB_DIR \
    --host 0.0.0.0 \
    --port 1442 \
    --since origin \
    --match "*"
else
  kupo \
    --node-socket node.sock \
    --node-config config.json \
    --workdir $DB_DIR \
    --host 0.0.0.0 \
    --port 1442 \
    --match "*"
fi
```

**Comment by KtorZ** [comment]
That's a fair point. I was thinking about this recently and, in principle it could be made idempotent if `--since` remains earlier than any of the database checkpoint. Then as you say, it can be used as a backup in case all checkpoints are invalid.

If however, there are checkpoints but --since provides a more recent point (such that there's a gap) then the behavior of the application is undefined and it should error.

Still, that would allow restarting the server from the same command line options 👍
