### ISSUE TITLE
Indexer should warn / exit when started with no matching patterns

### ISSUE THREAD

**Issue by KtorZ** [CardanoSolutions/kupo#22]
#### What Git revision are you using? 

v1.0.1

#### What operating system are you using, and which version?

- [ ] Linux / Ubuntu
- [x] Linux / Other
- [ ] OSX
- [ ] Windows

#### Describe what the problem is? 

It is possible to start kupo with no patterns (no `--match` for instance). In which index the indexer starts and just burn CPU processing blocks for nothing. 

#### What should be the expected behavior?

Arguably, the program should exit with an error indicating that with the given configuration, it'll be nothing but a radiator.

**Comment by waalge** [comment]
Can we get `--since` functionality on on-the-fly patterns? 

--- 

This is possibly some amount of complication for insufficient gain.  
It could involve an association of patterns to checkpoints. 
No patterns, then no checkpoints, and from that kupo infers there is nothing to do. 

For my use case there are no interesting addresses before the program launches.
The addresses of interests will be some that are "recently" new to use on chain.

The link to this issue is probably a bit too tenuous. If so I can make it a new one?

**Comment by waalge** [comment]
I've tried to say a more understandable thing in https://github.com/CardanoSolutions/kupo/discussions/27#discussion-4131361
