### ISSUE TITLE
Support pruning past a horizon

### ISSUE THREAD

**Issue by Quantumplation** [CardanoSolutions/kupo#36]
#### Describe your idea, in simple words.

It is possible to specify `--prune-spent` on startup, which will discard "spent" utxos.

It would be nice to be able to specify `--prune-spent {slotHorizon}`, which periodically discards spent UTXOs that are at least `{slotHorizon}` slots old.

#### Why is it a good idea?

Many applications need to see recently spent UTXOs (to trigger downstream actions, update internal state, etc.), but once they've seen and reacted to this, no longer need that data.

However, leaving off `--prune-spent` so that this data is accessible, the result sets will grow without bound, resulting in slowly degrading performance over time.  This is particularly egregious when tracking highly active addresses, such as the smart contract for a popular dApp.

(Note: this solves a similar problem to #37, but I submitted them as separate issues for separate discussion / implementation)

#### Are you willing to work on it yourself?
Willing? Yes; Able? Probably not.

**Comment by KtorZ** [comment]
Note that I believe this is now fixed as a side-effect of fixing the UTxO management bugs identified as part of #44. Indeed, it appeared that it is actually not safe at all to get rid of inputs _immediately_ because some spent inputs may become available again on a different chain-fork. 

To be safe, it is therefore necessary for Kupo to keep inputs around for at least `k=2160` blocks. This is at most `3k / f` seconds which is 36h on mainnet/testnet (with `f = 0.05`). 

Initially I was planning to "hide" those transient spent outputs from the API when given `--prune-utxo`. But since there's already a flag to do so, having the endpoint returns spent but not-yet-garbage-collected matches feels useful and would solve this particular issue unless you need such information to be available for longer than 36h?

**Comment by Quantumplation** [comment]
Yep, and this is exactly the window I was going to specify when configuring kupo myself :sweat_smile:

**Comment by KtorZ** [comment]
Okay. Calling this one done then :blush:
